name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd python-algorithms
        pip install -r requirements.txt
        pip install pytest  # For testing

    - name: Run tests
      run: |
        cd python-algorithms
        # Example: Run the backtest script (no assert, just check runs)
        python backtesting/example_ma_crossover.py || echo "Backtest completed (plot skipped in CI)"
        # Add pytest if tests added
        # pytest tests/

    - name: Lint Python
      uses: pre-commit/action@v3
      with:
        extra_args: python-algorithms --all-files
